// Code generated by github.com/Gardego5/gohtml/codegen; DO NOT EDIT.

package html

import "context"


// The `a` HTML element (or *anchor* element), with its `href`
// attribute, creates a hyperlink to webpages, files, email
// addresses, locations in the same page, or anything else a URL
// can address.
type A []any
func (tag A) Render(context.Context) RenderedHTML { return Element("a", tag...) }

type Abbr []any
func (tag Abbr) Render(context.Context) RenderedHTML { return Element("abbr", tag...) }

type Address []any
func (tag Address) Render(context.Context) RenderedHTML { return Element("address", tag...) }

type Area Attrs
func (tag Area) Render(context.Context) RenderedHTML { return AttrsElement("area", Attrs(tag)) }

type Article []any
func (tag Article) Render(context.Context) RenderedHTML { return Element("article", tag...) }

type Aside []any
func (tag Aside) Render(context.Context) RenderedHTML { return Element("aside", tag...) }

type Audio []any
func (tag Audio) Render(context.Context) RenderedHTML { return Element("audio", tag...) }

type B []any
func (tag B) Render(context.Context) RenderedHTML { return Element("b", tag...) }

type Base Attrs
func (tag Base) Render(context.Context) RenderedHTML { return AttrsElement("base", Attrs(tag)) }

type Bdi []any
func (tag Bdi) Render(context.Context) RenderedHTML { return Element("bdi", tag...) }

type Bdo []any
func (tag Bdo) Render(context.Context) RenderedHTML { return Element("bdo", tag...) }

type Blockquote []any
func (tag Blockquote) Render(context.Context) RenderedHTML { return Element("blockquote", tag...) }

type Body []any
func (tag Body) Render(context.Context) RenderedHTML { return Element("body", tag...) }

type Br Attrs
func (tag Br) Render(context.Context) RenderedHTML { return AttrsElement("br", Attrs(tag)) }

type Button []any
func (tag Button) Render(context.Context) RenderedHTML { return Element("button", tag...) }

type Canvas []any
func (tag Canvas) Render(context.Context) RenderedHTML { return Element("canvas", tag...) }

type Caption []any
func (tag Caption) Render(context.Context) RenderedHTML { return Element("caption", tag...) }

type Cite []any
func (tag Cite) Render(context.Context) RenderedHTML { return Element("cite", tag...) }

type Code []any
func (tag Code) Render(context.Context) RenderedHTML { return Element("code", tag...) }

type Col Attrs
func (tag Col) Render(context.Context) RenderedHTML { return AttrsElement("col", Attrs(tag)) }

type Colgroup []any
func (tag Colgroup) Render(context.Context) RenderedHTML { return Element("colgroup", tag...) }

type Data []any
func (tag Data) Render(context.Context) RenderedHTML { return Element("data", tag...) }

type Datalist []any
func (tag Datalist) Render(context.Context) RenderedHTML { return Element("datalist", tag...) }

type Dd []any
func (tag Dd) Render(context.Context) RenderedHTML { return Element("dd", tag...) }

type Del []any
func (tag Del) Render(context.Context) RenderedHTML { return Element("del", tag...) }

type Details []any
func (tag Details) Render(context.Context) RenderedHTML { return Element("details", tag...) }

type Dfn []any
func (tag Dfn) Render(context.Context) RenderedHTML { return Element("dfn", tag...) }

type Dialog []any
func (tag Dialog) Render(context.Context) RenderedHTML { return Element("dialog", tag...) }

type Div []any
func (tag Div) Render(context.Context) RenderedHTML { return Element("div", tag...) }

type Dl []any
func (tag Dl) Render(context.Context) RenderedHTML { return Element("dl", tag...) }

type Dt []any
func (tag Dt) Render(context.Context) RenderedHTML { return Element("dt", tag...) }

type Em []any
func (tag Em) Render(context.Context) RenderedHTML { return Element("em", tag...) }

type Embed Attrs
func (tag Embed) Render(context.Context) RenderedHTML { return AttrsElement("embed", Attrs(tag)) }

type Fieldset []any
func (tag Fieldset) Render(context.Context) RenderedHTML { return Element("fieldset", tag...) }

type Figcaption []any
func (tag Figcaption) Render(context.Context) RenderedHTML { return Element("figcaption", tag...) }

type Figure []any
func (tag Figure) Render(context.Context) RenderedHTML { return Element("figure", tag...) }

type Footer []any
func (tag Footer) Render(context.Context) RenderedHTML { return Element("footer", tag...) }

type Form []any
func (tag Form) Render(context.Context) RenderedHTML { return Element("form", tag...) }

type H1 []any
func (tag H1) Render(context.Context) RenderedHTML { return Element("h1", tag...) }

type H2 []any
func (tag H2) Render(context.Context) RenderedHTML { return Element("h2", tag...) }

type H3 []any
func (tag H3) Render(context.Context) RenderedHTML { return Element("h3", tag...) }

type H4 []any
func (tag H4) Render(context.Context) RenderedHTML { return Element("h4", tag...) }

type H5 []any
func (tag H5) Render(context.Context) RenderedHTML { return Element("h5", tag...) }

type H6 []any
func (tag H6) Render(context.Context) RenderedHTML { return Element("h6", tag...) }

type Head []any
func (tag Head) Render(context.Context) RenderedHTML { return Element("head", tag...) }

type Header []any
func (tag Header) Render(context.Context) RenderedHTML { return Element("header", tag...) }

type Hgroup []any
func (tag Hgroup) Render(context.Context) RenderedHTML { return Element("hgroup", tag...) }

type Hr Attrs
func (tag Hr) Render(context.Context) RenderedHTML { return AttrsElement("hr", Attrs(tag)) }

type Html []any
func (tag Html) Render(context.Context) RenderedHTML { return Element("html", tag...) }

type I []any
func (tag I) Render(context.Context) RenderedHTML { return Element("i", tag...) }

type Iframe []any
func (tag Iframe) Render(context.Context) RenderedHTML { return Element("iframe", tag...) }

type Img Attrs
func (tag Img) Render(context.Context) RenderedHTML { return AttrsElement("img", Attrs(tag)) }

type Input Attrs
func (tag Input) Render(context.Context) RenderedHTML { return AttrsElement("input", Attrs(tag)) }

type Ins []any
func (tag Ins) Render(context.Context) RenderedHTML { return Element("ins", tag...) }

type Kbd []any
func (tag Kbd) Render(context.Context) RenderedHTML { return Element("kbd", tag...) }

type Label []any
func (tag Label) Render(context.Context) RenderedHTML { return Element("label", tag...) }

type Legend []any
func (tag Legend) Render(context.Context) RenderedHTML { return Element("legend", tag...) }

type Li []any
func (tag Li) Render(context.Context) RenderedHTML { return Element("li", tag...) }

type Link Attrs
func (tag Link) Render(context.Context) RenderedHTML { return AttrsElement("link", Attrs(tag)) }

type Main []any
func (tag Main) Render(context.Context) RenderedHTML { return Element("main", tag...) }

type Map []any
func (tag Map) Render(context.Context) RenderedHTML { return Element("map", tag...) }

type Mark []any
func (tag Mark) Render(context.Context) RenderedHTML { return Element("mark", tag...) }

type Math []any
func (tag Math) Render(context.Context) RenderedHTML { return Element("math", tag...) }

type Menu []any
func (tag Menu) Render(context.Context) RenderedHTML { return Element("menu", tag...) }

type Menuitem Attrs
func (tag Menuitem) Render(context.Context) RenderedHTML { return AttrsElement("menuitem", Attrs(tag)) }

type Meta Attrs
func (tag Meta) Render(context.Context) RenderedHTML { return AttrsElement("meta", Attrs(tag)) }

type Meter []any
func (tag Meter) Render(context.Context) RenderedHTML { return Element("meter", tag...) }

type Nav []any
func (tag Nav) Render(context.Context) RenderedHTML { return Element("nav", tag...) }

type Noscript []any
func (tag Noscript) Render(context.Context) RenderedHTML { return Element("noscript", tag...) }

type Object []any
func (tag Object) Render(context.Context) RenderedHTML { return Element("object", tag...) }

type Ol []any
func (tag Ol) Render(context.Context) RenderedHTML { return Element("ol", tag...) }

type Optgroup []any
func (tag Optgroup) Render(context.Context) RenderedHTML { return Element("optgroup", tag...) }

type Option []any
func (tag Option) Render(context.Context) RenderedHTML { return Element("option", tag...) }

type Output []any
func (tag Output) Render(context.Context) RenderedHTML { return Element("output", tag...) }

type P []any
func (tag P) Render(context.Context) RenderedHTML { return Element("p", tag...) }

type Param Attrs
func (tag Param) Render(context.Context) RenderedHTML { return AttrsElement("param", Attrs(tag)) }

type Picture []any
func (tag Picture) Render(context.Context) RenderedHTML { return Element("picture", tag...) }

type Pre []any
func (tag Pre) Render(context.Context) RenderedHTML { return Element("pre", tag...) }

type Progress []any
func (tag Progress) Render(context.Context) RenderedHTML { return Element("progress", tag...) }

type Q []any
func (tag Q) Render(context.Context) RenderedHTML { return Element("q", tag...) }

type Rb []any
func (tag Rb) Render(context.Context) RenderedHTML { return Element("rb", tag...) }

type Rp []any
func (tag Rp) Render(context.Context) RenderedHTML { return Element("rp", tag...) }

type Rt []any
func (tag Rt) Render(context.Context) RenderedHTML { return Element("rt", tag...) }

type Rtc []any
func (tag Rtc) Render(context.Context) RenderedHTML { return Element("rtc", tag...) }

type Ruby []any
func (tag Ruby) Render(context.Context) RenderedHTML { return Element("ruby", tag...) }

type S []any
func (tag S) Render(context.Context) RenderedHTML { return Element("s", tag...) }

type Samp []any
func (tag Samp) Render(context.Context) RenderedHTML { return Element("samp", tag...) }

type Script []any
func (tag Script) Render(context.Context) RenderedHTML { return Element("script", tag...) }

type Search []any
func (tag Search) Render(context.Context) RenderedHTML { return Element("search", tag...) }

type Section []any
func (tag Section) Render(context.Context) RenderedHTML { return Element("section", tag...) }

type Select []any
func (tag Select) Render(context.Context) RenderedHTML { return Element("select", tag...) }

type Slot []any
func (tag Slot) Render(context.Context) RenderedHTML { return Element("slot", tag...) }

type Small []any
func (tag Small) Render(context.Context) RenderedHTML { return Element("small", tag...) }

type Source Attrs
func (tag Source) Render(context.Context) RenderedHTML { return AttrsElement("source", Attrs(tag)) }

type Span []any
func (tag Span) Render(context.Context) RenderedHTML { return Element("span", tag...) }

type Strong []any
func (tag Strong) Render(context.Context) RenderedHTML { return Element("strong", tag...) }

type Style []any
func (tag Style) Render(context.Context) RenderedHTML { return Element("style", tag...) }

type Sub []any
func (tag Sub) Render(context.Context) RenderedHTML { return Element("sub", tag...) }

type Summary []any
func (tag Summary) Render(context.Context) RenderedHTML { return Element("summary", tag...) }

type Sup []any
func (tag Sup) Render(context.Context) RenderedHTML { return Element("sup", tag...) }

type Svg []any
func (tag Svg) Render(context.Context) RenderedHTML { return Element("svg", tag...) }

type Table []any
func (tag Table) Render(context.Context) RenderedHTML { return Element("table", tag...) }

type Tbody []any
func (tag Tbody) Render(context.Context) RenderedHTML { return Element("tbody", tag...) }

type Td []any
func (tag Td) Render(context.Context) RenderedHTML { return Element("td", tag...) }

type Template []any
func (tag Template) Render(context.Context) RenderedHTML { return Element("template", tag...) }

type Textarea []any
func (tag Textarea) Render(context.Context) RenderedHTML { return Element("textarea", tag...) }

type Tfoot []any
func (tag Tfoot) Render(context.Context) RenderedHTML { return Element("tfoot", tag...) }

type Th []any
func (tag Th) Render(context.Context) RenderedHTML { return Element("th", tag...) }

type Thead []any
func (tag Thead) Render(context.Context) RenderedHTML { return Element("thead", tag...) }

type Time []any
func (tag Time) Render(context.Context) RenderedHTML { return Element("time", tag...) }

type Title []any
func (tag Title) Render(context.Context) RenderedHTML { return Element("title", tag...) }

type Tr []any
func (tag Tr) Render(context.Context) RenderedHTML { return Element("tr", tag...) }

type Track Attrs
func (tag Track) Render(context.Context) RenderedHTML { return AttrsElement("track", Attrs(tag)) }

type U []any
func (tag U) Render(context.Context) RenderedHTML { return Element("u", tag...) }

type Ul []any
func (tag Ul) Render(context.Context) RenderedHTML { return Element("ul", tag...) }

type Var []any
func (tag Var) Render(context.Context) RenderedHTML { return Element("var", tag...) }

type Video []any
func (tag Video) Render(context.Context) RenderedHTML { return Element("video", tag...) }

type Wbr Attrs
func (tag Wbr) Render(context.Context) RenderedHTML { return AttrsElement("wbr", Attrs(tag)) }
