// Code generated by github.com/Gardego5/gohtml/codegen; DO NOT EDIT.

package html

{{range .}}
{{if .Desc}}// {{.Desc}}{{end}}
type {{.Name | Title}} {{if .Void}}Attrs{{else}}[]any{{end}}
func (tag {{.Name | Title}}) Render() RenderedHTML { return {{if .Void}}AttrsElement("{{.Name}}"{{else}}Element("{{.Name}}"{{end}}, tag...) }{{end}}
