// Code generated by github.com/Gardego5/gohtml/codegen; DO NOT EDIT.

package html

import "context"

{{range .}}
{{if .Desc}}// {{.Desc}}{{end}}
type {{.Name | Title}} {{if .Void}}Attrs{{else}}[]any{{end}}
func (tag {{.Name | Title}}) Render(context.Context) RenderedHTML { return {{if .Void}}AttrsElement("{{.Name}}", Attrs(tag)){{else}}Element("{{.Name}}", tag...){{end}} }{{end}}
